-- AlterTable
ALTER TABLE "Course" ADD COLUMN     "discountPrice" DOUBLE PRECISION,
ADD COLUMN     "price" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "showPrice" BOOLEAN NOT NULL DEFAULT true;
