#!/bin/bash
# start_services.sh
# This script starts your Node.js and Prisma services

echo "Starting npm service..."
(cd /root/Gad/web/APIs/vibSolutionsAPI && npm start) &

echo "Starting NestJS backend (dev mode)..."
(cd /root/Gad/web/APIs/vibSolutionsAPI/backend && npm run start:dev) &

echo "Opening Prisma Studio..."
(cd /root/Gad/web/APIs/vibSolutionsAPI/backend && pnpm exec prisma studio) &

echo "All services launched!"
wait
